package it.polimi.ingsw.client.GUI;

import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;

public class GuiAssets {
    public static final String whiteColorText = "White";
    public static final String firstWizardText = "Gandalf";
    public static final String blackColorText = "Black";
    public static final String secondWizardText = "Baljeet";
    public static final String greyColorText = "Grey";
    public static final String thirdWizardText = "Sabrina";
    public static final String fourthWizardText = "Kenji";
    public static final String pinkCreatureText = "P";
    public static final String redCreatureText = "R";
    public static final String greenCreatureText = "G";
    public static final String blueCreatureText = "B";
    public static final String yellowCreatureText = "Y";
    public static final String moveStudentsCode = "MS:";
    public static final String selectCreatureCode = "C:";
    public static String gameTitle = "Eryantis";
    public static Color backgroundColor = Color.rgb(131, 187, 218);
    public static Font titleFont = Font.font("Papyrus", FontWeight.LIGHT, 160);
    public static String joinButton = "Join";
    public static String twoPlayersButton = "Two Players";
    public static String threePlayersButton = "Three Players";
    public static String basicRulesButton = "Basic Rules";
    public static String basicRulesCode = "0";
    public static String advancedRulesButton = "Advanced Rules";
    public static String advancedRulesCode = "1";
    public static String provideUsernameText = "Provide your username";
    public static final String currentPhasePrefix = "The current game phase is: ";
    public static final String moveStudentsText = "Move the students";
    public static final String moveMotherNatureText = "Move Mother Nature";
    public static final String selectCloudText = "Select a cloud";
    public static final String chooseCharacterText = " or Select a Character";
    public static final String selectAssistantText = "Select an Assistant";
    public static final String commandSeparator = ":";
    public static final String moveMotherNatureCode = "MMN:";
    public static final String selectDestinationIslandCode = ":I:";
    public static final String selectCloudCode = "SC:";
    public static final String playCharacterCode = "PC:";
    public static final String entranceHeaderText = "Entrance";
    public static final String diningRoomHeaderText = "Dining Room";
    public static final String professorsHeaderText = "Professors";
    public static final String assistantHeaderText = "Assistant";
    public static final String coinHeaderText = "Coins";
    public static String whiteColorCode = "1";
    public static String blackColorCode = "2";
    public static String greyColorCode = "3";
    public static String firstWizardCode = "1";
    public static String secondWizardCode = "2";
    public static String thirdWizardCode = "3";
    public static String fourthWizardCode = "4";
    public static int smallSpacing = 5;
    public static int mediumSpacing = 10;
    public static int motherNatureHeight = 28;
    public static int motherNatureWidth = 20;
    public static int islandHeight = 130;
    public static int islandWidth = 134;
    public static int cloudHeight = 140;
    public static int cloudWidth = 140;
    public static int assistantHeight = 146;
    public static int assistantWidth = 100;
    public static int characterHeight = 200;
    public static int characterWidth = 133;
    public static int creatureHeight = 100;
    public static int creatureWidth = 100;
    public static int coinHeight = 50;
    public static int coinWidth = 50;
    public static int wizardHeight = 33;
    public static int wizardWidth = 33;
    public static int playerRadius = 25;
    public static int playerContentHeight = 20;
    public static int playerContentWidth = 20;
    public static int centerX = 100;
    public static int centerY = 100;
    public static int islandRadius = 300;
    public static int cloudRadius = 100;
    public static int islandContentCenter = 0;
    public static int islandContentRadius = 50;
    public static int islandContentComponents = 7;
    public static int cloudContentRadius = 40;
    public static int cloudContentComponents = 5;
    public static int noErrorCode = 0;
}
