package it.polimi.ingsw.view.GUI;

public enum GUIPhases {
    SELECT_CREATURE,
    SELECT_DESTINATION,
    SELECT_CREATURE_FOR_CHARACTER,
    SELECT_DESTINATION_ISLAND,
    SELECT_ISLAND,
    SELECT_SOURCE_CREATURE,
    SELECT_SOURCE_CREATURE_TO_SWAP,
    SELECT_MMN_MOVEMENTS,
    END;

}
