package it.polimi.ingsw;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class MotherNatureTest {

    MotherNature mn ;

    @BeforeEach
    public void createMn(){
        mn = new MotherNature();
    }

    /**
     * This tests that every possible value is generated by MotherNature
     * random number generator
     */
    @Test
    public void MotherNatureRandomValuesTest(){
        List<Integer> values = new ArrayList<>();
        for (int i = 0; i < 12; i++) {
            values.add(0);
        }
        values.add(mn.getCurrentIsland(),values.get(mn.getCurrentIsland())+1);
        for (int i = 0; i < 100; i++) {
            mn = new MotherNature();
            values.add(mn.getCurrentIsland(),values.get(mn.getCurrentIsland())+1);
        }

        for(int x=0; x<12; x++){
            System.out.print(values.get(x)+" ");
            assertTrue(values.get(x)!=0);
        }
    }

}